### ISSUE TITLE
Change Tag to ClientSource in Person's field

### ISSUE THREAD

**Issue by Joven-Heng** [AY2021S1-CS2103-T16-2/tp#11]
Client source field should be something similar to the description field. 
Eg: JC friend/ Javier's (CS2103) Father/ Met him at a Tampines Roadshow.

This field should be an optional string. 

Examples of usage:
add n/NAME [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [o/NOTE] [s/SOURCE]...

**Comment by WeiJie96** [comment]
Ensure that source should be <= 50 characters.
